#!/usr/bin/env python3
"""Curate the genome set for the TCS pipeline.

Pre-pipeline step (Option A): produces data/reference/curated_genome_list.txt
which the Snakefile reads at startup. The curated list:
  - Caps over-represented genera at --max_per_genus (default 5)
  - Always includes all RECOMMENDED_GENOMES accessions regardless of cap
  - Within a capped genus, prefers: Complete Genome > Chromosome > Scaffold > Contig,
    then alphabetical full_id for determinism
  - Writes full_ids (accession_asmname) matching data/genomes/ folder names

Usage (run once before pipeline execution):
  python scripts/curate_genome_set.py \\
      --assembly_summary data/metadata/assembly_summary.txt \\
      --genome_dir data/genomes \\
      --output data/reference/curated_genome_list.txt \\
      --report data/reference/curation_report.txt \\
      --max_per_genus 5

Rationale: 83% of the original 1,475-genome set came from 3 genera
(Pseudomonas 32%, Campylobacter 32%), inflating cluster sizes and
phase coherence scores. A 5-per-genus cap preserves species-level
diversity within a genus while removing pseudo-replication.
(Laub 2007; Capra & Laub 2012 Cell)
"""

import argparse
import os
import sys
from pathlib import Path

import pandas as pd

from tcs_constants import ASSEMBLY_LEVEL_PRIORITY, RECOMMENDED_GENOMES


def load_assembly_summary(path: str) -> pd.DataFrame:
    df = pd.read_csv(
        path, sep="\t", skiprows=2, header=None,
        usecols=[0, 7, 11, 15, 5],
        names=["accession", "organism_name", "assembly_level", "asm_name", "taxid"],
        low_memory=False,
    )
    df["full_id"] = df["accession"] + "_" + df["asm_name"]
    df["genus"] = df["organism_name"].str.split().str[0]
    df["level_rank"] = df["assembly_level"].map(ASSEMBLY_LEVEL_PRIORITY).fillna(99)
    return df


def get_downloaded_genomes(genome_dir: str) -> set:
    """Return set of folder names (full_ids) in genome_dir."""
    return {d for d in os.listdir(genome_dir) if d.startswith("GCF_")}


def match_to_assembly(downloaded: set, asm_df: pd.DataFrame) -> pd.DataFrame:
    """Match downloaded genome folders to assembly_summary rows.

    Matches on both short accession (GCF_000005845.2) and full_id
    (GCF_000005845.2_ASM584v2) because data/genomes/ may contain either format.
    """
    return asm_df[
        asm_df["accession"].isin(downloaded) | asm_df["full_id"].isin(downloaded)
    ].copy()


def curate(matched: pd.DataFrame, max_per_genus: int) -> tuple:
    """Return (curated_full_ids: list, genus_counts: dict).

    Always preserves RECOMMENDED_GENOMES. Caps remaining genomes per genus.
    Selection within a capped genus: best assembly level, then alphabetical
    full_id for determinism.

    Returns full_ids (e.g. GCF_000005845.2_ASM584v2) so the Snakefile can
    match against data/genomes/ folder names with a direct set lookup.
    """
    protected_accs = set(RECOMMENDED_GENOMES.values())

    matched = matched.copy()
    matched["is_protected"] = matched["accession"].isin(protected_accs)

    # Sort: protected first within genus, then by assembly quality, then full_id
    matched = matched.sort_values(
        ["genus", "is_protected", "level_rank", "full_id"],
        ascending=[True, False, True, True],
    )

    selected: list[str] = []
    genus_counts: dict[str, dict] = {}

    for genus, grp in matched.groupby("genus"):
        protected_rows = grp[grp["is_protected"]]
        other_rows = grp[~grp["is_protected"]]

        n_available = len(grp)
        n_protected = len(protected_rows)
        slots_remaining = max(0, max_per_genus - n_protected)

        # Write full_id (accession_asmname) so Snakefile filter is a direct set lookup
        kept = list(protected_rows["full_id"])
        kept += list(other_rows["full_id"].iloc[:slots_remaining])
        dropped = list(other_rows["full_id"].iloc[slots_remaining:])

        selected.extend(kept)
        genus_counts[genus] = {
            "available": n_available,
            "kept": len(kept),
            "dropped": len(dropped),
            "protected": n_protected,
        }

    return selected, genus_counts


def write_report(
    original: int,
    curated: list,
    genus_counts: dict,
    report_path: str,
    max_per_genus: int,
) -> None:
    lines = [
        "# Genome Set Curation Report",
        f"# Generated by curate_genome_set.py (max_per_genus={max_per_genus})",
        "",
        f"Original genome count : {original}",
        f"Curated genome count  : {len(curated)}",
        f"Genomes removed       : {original - len(curated)}",
        "",
        f"{'Genus':<30} {'Available':>10} {'Kept':>6} {'Dropped':>8} {'Protected':>10}",
        "-" * 68,
    ]
    for genus, c in sorted(genus_counts.items(), key=lambda x: -x[1]["available"]):
        lines.append(
            f"{genus:<30} {c['available']:>10} {c['kept']:>6}"
            f" {c['dropped']:>8} {c['protected']:>10}"
        )
    Path(report_path).write_text("\n".join(lines) + "\n")
    print(f"Curation report written to: {report_path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--assembly_summary", required=True,
                        help="data/metadata/assembly_summary.txt")
    parser.add_argument("--genome_dir", required=True,
                        help="data/genomes/ directory")
    parser.add_argument("--output", required=True,
                        help="Path to write curated_genome_list.txt")
    parser.add_argument("--report", required=True,
                        help="Path to write curation_report.txt")
    parser.add_argument("--max_per_genus", type=int, default=5,
                        help="Max genomes per genus (default 5). "
                             "Recommended reference organisms are always kept.")
    args = parser.parse_args()

    asm = load_assembly_summary(args.assembly_summary)
    downloaded = get_downloaded_genomes(args.genome_dir)
    matched = match_to_assembly(downloaded, asm)

    if matched.empty:
        print("ERROR: no genomes matched assembly_summary.txt", file=sys.stderr)
        sys.exit(1)

    curated, genus_counts = curate(matched, args.max_per_genus)

    write_report(len(matched), curated, genus_counts, args.report, args.max_per_genus)

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        "# Curated genome list — generated by curate_genome_set.py\n"
        f"# max_per_genus={args.max_per_genus}\n"
        "# Format: full_id (accession_asmname) — matches data/genomes/ folder names\n"
        + "\n".join(curated)
        + "\n"
    )
    print(f"Curated list ({len(curated)} genomes) written to: {args.output}")


if __name__ == "__main__":
    main()
